Fix ImageSlidesController#create action
Position was nil while creating the first element.
Error was:
  NoMethodError - undefined method `+' for nil:NilClass: